import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * SBIM 文档侧边栏配置
 * 采用混合策略：手动定义顶层结构 + 自动生成内容目录
 *
 * 设计原则：
 * 1. 顶层分类手动管理，确保用户体验和导航逻辑
 * 2. 具体内容目录自动生成，减少维护成本
 * 3. 使用 ref 类型避免文档归属歧义
 * 4. 为每个分类提供索引页面，增强可用性
 */
const sidebars: SidebarsConfig = {
  // 主文档侧边栏 - 简化版，只包含现有内容
  tutorialSidebar: [
    // 欢迎页面
    {
      type: 'doc',
      id: 'intro',
      label: '欢迎使用',
      className: 'sidebar-welcome',
    },

    // 快速开始 - 现有内容
    {
      type: 'category',
      label: '快速开始',
      link: {
        type: 'doc',
        id: 'getting-started/index',
      },
      collapsed: false,
      className: 'sidebar-getting-started',
      items: [
        { type: 'autogenerated', dirName: 'getting-started' },
      ],
    },

    // API 文档 - 现有内容
    {
      type: 'category',
      label: 'API 文档',
      link: {
        type: 'doc',
        id: 'cloud-api/overview',
      },
      collapsed: true,
      className: 'sidebar-cloud-api',
      items: [
        { type: 'autogenerated', dirName: 'cloud-api' },
      ],
    },

    // 用户指南
    {
      type: 'category',
      label: '用户指南',
      link: {
        type: 'doc',
        id: 'guides/index',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'guides' },
      ],
    },

    // FAQ 系统
    {
      type: 'category',
      label: '常见问题',
      link: {
        type: 'doc',
        id: 'faq/index',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'faq' },
      ],
    },

    // 开发者资源
    {
      type: 'category',
      label: '开发者资源',
      link: {
        type: 'doc',
        id: 'developers/index',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'developers' },
      ],
    },

    // 分隔线
    {
      type: 'html',
      value: '<hr class="sidebar-divider">',
      defaultStyle: true,
    },

    // 外部链接
    {
      type: 'link',
      label: '官方网站',
      href: 'https://sb.im',
      className: 'sidebar-external-link',
    },
    {
      type: 'link',
      label: '技术支持',
      href: 'mailto:support@sb.im',
      className: 'sidebar-external-link',
    },
  ],
};

export default sidebars;
