import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * API对接文档侧边栏配置
 * 专注于API对接相关的文档内容
 */
const sidebars: SidebarsConfig = {
  // API对接文档侧边栏
  tutorialSidebar: [
    // API 对接概述

    // 更新记录
    {
      type: 'doc',
      id: 'index',
      label: '更新记录',
      className: 'sidebar-welcome',
    },


    //
    {
      type: 'category',
      label: '接口概述',
      link: {
        type: 'doc',
        id: 'cloud-api/index',
      },
      collapsed: false,
      className: 'sidebar-cloud-api',
      items: [
        { type: 'autogenerated', dirName: 'cloud-api' },
      ],
    },

    // 开发者资源
    {
      type: 'category',
      label: '快速对接',
      link: {
        type: 'doc',
        id: 'developers/index',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'developers' },
      ],
    },

    // FAQ 系统
    {
      type: 'category',
      label: '常见问题',
      link: {
        type: 'doc',
        id: 'faq/index',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'faq' },
      ],
    },

    // 分隔线
    {
      type: 'html',
      value: '<hr class="sidebar-divider">',
      defaultStyle: true,
    },

      // 搜索页面
      {
          type: 'link',
          label: '搜索文档',
          href: '/search',
          className: 'sidebar-search-link',
      },
    // 外部链接
    {
      type: 'link',
      label: '官方网站',
      href: 'https://sb.im',
      className: 'sidebar-external-link',
    },
    {
      type: 'link',
      label: '技术支持',
      href: 'mailto:support@sb.im',
      className: 'sidebar-external-link',
    },

  ],
};

export default sidebars;
