import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 主要文档侧边栏 - 简化版本，只包含现有的文档
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '快速入门',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '使用指南',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: '常见问题',
      items: [
        'faq/faq',
        {
          type: 'category',
          label: '快速入门问题',
          items: [{type: 'autogenerated', dirName: 'faq/getting-started'}],
        },
        {
          type: 'category',
          label: '技术支持问题',
          items: [{type: 'autogenerated', dirName: 'faq/technical'}],
        },
        {
          type: 'category',
          label: '计费相关问题',
          items: [{type: 'autogenerated', dirName: 'faq/billing'}],
        },
        {
          type: 'category',
          label: '故障排除问题',
          items: [{type: 'autogenerated', dirName: 'faq/troubleshooting'}],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
