name: 测试构建

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: 安装依赖
        run: npm ci

      - name: 类型检查
        run: npm run typecheck

      - name: 测试构建
        run: npm run build
